site_name: Ansible Sensu
site_url: https://galaxy.ansible.com/list#/roles/3802
repo_url: https://github.com/cmacrae/ansible-sensu/
site_description: An Ansible role to deploy a fully dynamic Sensu stack!
site_author: Calum MacRae

pages:
  - [ 'index.md', 'Index' ]
  - [ 'example_infra.md', 'Usage', 'Example infrastructure layout' ]
  - [ 'single_master.md', 'Usage', 'Deploy the stack to a single node' ]
  - [ 'custom_client_config.md', 'Usage', 'Custom client configuration' ]
  - [ 'deploy_plugins.md', 'Usage', 'Deployment of handlers/filters/mutators' ]
  - [ 'sensitive_info.md', 'Usage', 'Sensitive information in version control' ]
  - [ 'dynamic_data.md','Conventions','Dynamic data store' ]
  - [ 'dynamic_checks.md','Conventions','Dynamic check deployment' ]
  - [ 'afewwords.md','About','A few words from the author' ]
  - [ 'license.md','About','License' ]
