---
scenario:
  name: fedora
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: fedora-26
    image: dokken/fedora-26
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fedora-27
    image: dokken/fedora-27
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fedora-28
    image: dokken/fedora-latest
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: timer,profile_tasks
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      poll_interval: 3
      forks: 100
    connection:
      pipelining: true
  playbooks:
    prepare: ../shared/prepare.yml
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/playbook.yml
    verify: ../shared/verify.yml
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        sensu_master: true
        sensu_include_dashboard: true
        rabbitmq_server: true
        redis_server: true
        rabbitmq_host: "{{ ansible_hostname }}"
        redis_host: "{{ ansible_hostname }}"
        sensu_api_host: "{{ ansible_hostname }}"
        ansible_default_ipv4:
          address: 127.0.0.1
    host_vars:
      fedora-26:
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.2.27/el/7/inspec-2.2.27-1.el7.x86_64.rpm
        inspec_download_sha256sum: 9c0c1f3b9e14737d40554e0791658187d91c5eb0640f9514602945c5633399df
      fedora-27:
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.2.27/el/7/inspec-2.2.27-1.el7.x86_64.rpm
        inspec_download_sha256sum: 9c0c1f3b9e14737d40554e0791658187d91c5eb0640f9514602945c5633399df
      fedora-28:
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.2.27/el/7/inspec-2.2.27-1.el7.x86_64.rpm
        inspec_download_sha256sum: 9c0c1f3b9e14737d40554e0791658187d91c5eb0640f9514602945c5633399df
verifier:
  name: inspec
  directory: ../shared/tests/
  lint:
    name: rubocop
