---
# tasks/client.yml: Deploy various client-side configurations for Sensu
  
  - include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - default.yml

  - name: Deploy Sensu client RabbitMQ configuration
    template: dest="{{ sensu_config_path }}/conf.d/rabbitmq.json"
              owner={{ sensu_user_name }} group={{ sensu_group_name }}
              src=rabbitmq.json.j2
    notify: restart sensu-client service

  - name: Deploy Sensu client service configuration
    template: dest="{{ sensu_config_path }}/conf.d/client.json"
              owner={{ sensu_user_name }} group={{ sensu_group_name }}
              src={{ sensu_client_config  }}
    notify: restart sensu-client service

  - include: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}/client.yml"
      - "{{ ansible_os_family }}/client.yml"

  - name: Ensure Sensu client service is running
    service: name=sensu-client state=started enabled=yes
