---
# tasks/main.yml: "Master" playbook for the cmacrae.sensu role

  - include: "{{ item }} tags=setup"
    with_first_found:
      - "{{ ansible_distribution }}/main.yml"
      - "{{ ansible_os_family }}/main.yml"
      
  - include: ssl.yml tags=ssl

  - include: rabbit.yml tags=rabbitmq
    when: rabbitmq_server

  - include: redis.yml tags=redis
    when: redis_server

  - include: server.yml tags=server
    when: sensu_master

  - include: dashboard.yml tags=dashboard
    when: sensu_include_dashboard
    
  - include: client.yml tags=client

  - include: plugins.yml tags=plugins
    when: sensu_include_plugins
