---

  - name: Deploy Sensu server API configuration
    template: dest={{ sensu_config_path }}/conf.d/api.json
              owner={{ sensu_user_name }} group={{ sensu_group_name }}
              src=sensu-api.json.j2
    notify: restart sensu-api service

  - name: Deploy Sensu Redis configuration
    template: dest={{ sensu_config_path }}/conf.d/redis.json
              owner={{ sensu_user_name }} group={{ sensu_group_name }}
              src=sensu-redis.json.j2
    notify: restart sensu-api service

  - include: "{{ ansible_distribution }}/server.yml"

  - name: Ensure Sensu server service is running
    service: name=sensu-server state=started enabled=yes

  - name: Ensure Sensu API service is running
    service: name=sensu-api state=started enabled=yes
