---

# RabbitMQ server properties
rabbitmq_config_path: /etc/rabbitmq
rabbitmq_config_template: rabbitmq.config.j2
rabbitmq_host: "{{ groups['rabbitmq_servers'][0] }}"
rabbitmq_port: 5671
rabbitmq_pkg_state: present
rabbitmq_server: false
rabbitmq_sensu_user_name: sensu
rabbitmq_sensu_password: sensu
rabbitmq_sensu_vhost: /sensu

# Redis server properties
redis_host: "{{ groups['redis_servers'][0] }}"
redis_server: false
redis_pkg_repo: ~
redis_pkg_state: present
redis_port: 6379

# Sensu/Uchiwa user/group/service properties
sensu_api_host: "{{ groups['sensu_masters'][0] }}"
sensu_api_port: 4567
sensu_api_ssl: "false"
sensu_api_user_name: admin
sensu_api_password: secret
sensu_api_uchiwa_path: ''
sensu_api_timeout: 5000
sensu_client_config: client.json.j2
sensu_config_path: /etc/sensu
sensu_gem_state: present
sensu_plugin_gem_state: present
sensu_group_name: sensu
sensu_include_plugins: true
sensu_include_dashboard: false
sensu_master: false
sensu_user_name: sensu

# Sensu/RabbitMQ SSL certificate properties
sensu_ssl_gen_certs: true
sensu_ssl_client_cert: "{{ dynamic_data_store }}/{{ groups['sensu_masters'][0] }}/{{ sensu_config_path }}/ssl_generation/ssl_certs/client/cert.pem"
sensu_ssl_client_key: "{{ dynamic_data_store }}/{{ groups['sensu_masters'][0] }}/{{ sensu_config_path }}/ssl_generation/ssl_certs/client/key.pem"
sensu_ssl_server_cacert: "{{ dynamic_data_store }}/{{ groups['sensu_masters'][0] }}/{{ sensu_config_path }}/ssl_generation/ssl_certs/sensu_ca/cacert.pem"
sensu_ssl_server_cert: "{{ dynamic_data_store }}/{{ groups['sensu_masters'][0] }}/{{ sensu_config_path }}/ssl_generation/ssl_certs/server/cert.pem"
sensu_ssl_server_key: "{{ dynamic_data_store }}/{{ groups['sensu_masters'][0] }}/{{ sensu_config_path }}/ssl_generation/ssl_certs/server/key.pem"
  
# Uchiwa properties
uchiwa_dc_name: ~
uchiwa_path: /opt/uchiwa
uchiwa_redis_use_ssl: false
uchiwa_user_name: admin
uchiwa_password: admin
uchiwa_port: 3000
uchiwa_refresh: 5
uchiwa_pkg_download_md5: ~
uchiwa_pkg_download_path: ~
uchiwa_pkg_download_url: ~
