---
# tasks/Ubuntu/redis.yml: Deploy Redis
# Specific to Ubuntu

  - include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - default.yml

  - name: Ensure the Redis APT repo is present
    apt_repository: repo={{ redis_pkg_repo }}
                    state=present update_cache=yes

  - name: Ensure Redis is installed
    apt: name=redis-server state={{ redis_pkg_state }}
         update_cache=yes

  - name: Deploy Redis systemd service manifest
    copy: src=ubuntu_redis_systemd.service
          dest=/etc/systemd/system/redis-server.service
