---
# tasks/Ubuntu/redis.yml: Deploy Redis
# Specific to Ubuntu

  - include_vars: ../../vars/{{ ansible_distribution }}.yml

  - name: Ensure the Redis APT repo is present
    apt_repository: repo={{ redis_pkg_repo }}
                    state=present update_cache=yes

  - name: Ensure Redis is installed
    apt: name=redis-server state={{ redis_pkg_state }}
         update_cache=yes

  - name: Deploy Redis systemd service manifest
    copy: src=../../files/ubuntu_redis_systemd.service
          dest=/etc/systemd/system/redis.service
