---
# tasks/SmartOS/server.yml: Deploy the necessary configuration for
# a Sensu 'master' node.
# Specific to SmartOS

  - name: Deploy Sensu server service manifest
    template: dest=/opt/local/lib/svc/manifest/sensu-server.xml
              src=sensu-server.smartos_smf_manifest.xml.j2
              owner=root group=root mode=644
    notify: import sensu-server service

  - name: Deploy Sensu API service manifest
    template: dest=/opt/local/lib/svc/manifest/sensu-api.xml
              src=sensu-api.smartos_smf_manifest.xml.j2
              owner=root group=root mode=644
    notify: import sensu-api service
 
  - name: Initial import of Sensu server service
    command: /usr/sbin/svccfg import /opt/local/lib/svc/manifest/sensu-server.xml
    args:
      creates: "/var/svc/log/application-sensu-server:default.log"
        
  - name: Initial import of Sensu API service
    command: /usr/sbin/svccfg import /opt/local/lib/svc/manifest/sensu-api.xml
    args:
      creates: "/var/svc/log/application-sensu-api:default.log"
