---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: windows-ltsc2016
    image: microsoft/windowsservercore:ltsc2016
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: timer,profile_tasks
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      poll_interval: 3
      forks: 100
    connection:
      pipelining: true
  playbooks:
    prepare: ../shared/prepare.yml
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/playbook.yml
    verify: ../shared/verify.yml
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        sensu_master: true
        sensu_include_dashboard: true
        rabbitmq_server: true
        redis_server: true
        rabbitmq_host: "{{ ansible_hostname }}"
        redis_host: "{{ ansible_hostname }}"
        sensu_api_host: "{{ ansible_hostname }}"
        ansible_default_ipv4:
          address: 127.0.0.1
    host_vars:
      windows-ltsc2016:
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.2.16/windows/2016/inspec-2.2.16-1-x64.msi
        inspec_download_sha256sum: 468452795abfd018f0eab31f9e5380b5bfadddf894bba751f40f8c20dc38a471
scenario:
  name: windows
verifier:
  name: inspec
  lint:
    name: rubocop
